import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

const store = new Vuex.Store({
  state: {
    selected:null,
    remove:false,
    slots: [
      {number:1,object:null},
      {number:2,object:null},
      {number:3,object:null},
      {number:4,object:null},
      {number:5,object:null},
      {number:6,object:null},
      {number:7,object:null},
      {number:8,object:null},
      {number:9,object:null},
      {number:10,object:null},
      {number:11,object:null},
      {number:12,object:null},
      {number:13,object:null},
      {number:14,object:null},
      {number:15,object:null},
      {number:16,object:null},
      {number:17,object:null},
      {number:18,object:null},
      {number:19,object:null},
      {number:20,object:null},
      {number:21,object:null},
      {number:22,object:null},
      {number:23,object:null},
      {number:24,object:null},
      {number:25,object:null},
      {number:26,object:null},
      {number:27,object:null},
      {number:28,object:null},
      {number:29,object:null},
      {number:30,object:null},
      {number:31,object:null},
      {number:32,object:null},
      {number:33,object:null},
      {number:34,object:null},
      {number:35,object:null},
      {number:36,object:null},
      {number:37,object:null},
      {number:38,object:null},
      {number:39,object:null},
      {number:40,object:null},
      {number:41,object:null},
      {number:42,object:null},
      {number:43,object:null},
      {number:44,object:null},
      {number:45,object:null},
      {number:46,object:null},
      {number:47,object:null},
      {number:48,object:null},
      {number:49,object:null},
      {number:50,object:null},
      {number:51,object:null},
      {number:52,object:null},
      {number:53,object:null},
      {number:54,object:null},
      {number:55,object:null},
      {number:56,object:null},
      {number:57,object:null},
      {number:58,object:null},
      {number:59,object:null},
      {number:60,object:null},
      {number:61,object:null},
      {number:62,object:null},
      {number:63,object:null},
      {number:64,object:null},
    ],
    objects:[
      'silla',
      'mesa',
      'alfombra'
    ]
  },
})

export default store
